baseURL: "https://alextekle.com/" 
title: Alexander Tekle
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    description: ""
    author: Alex Tekle
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alex Tekle
          subtitle: "I am a software engineer with an interest in deep learning and natural language processing. In my free time I enjoy working out, making coffee, being involved in my community, and listening to new music."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Alex Tekle

    socialIcons:
        - name: Linkedin
          url: https://www.linkedin.com/in/alexandertekle/
        - name: CV
          url: /resume.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=xtnfHJ4AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/alexandertekle
        - name: Substack
          url: https://medium.com/@alexandertekle
        - name: Email
          url: mailto:tekle.alexander@gmail.com
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Alex Tekle"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2